### ISSUE TITLE
Pretrained model without Flamingo Policy

### ISSUE THREAD

**Issue by mbreuss** [liufanfanlff/RoboUniview#1]
Hi,

thanks for sharing this cool work and code! The performance on ABC is very impressive. 
Did you ever test your model with another policy that is not a VLM? If so, what was the results?

**Comment by liufanfanlff** [comment]
Thank you for your attention and recognition of our work.  We have tried combining it with [3D Diffuser Actor ](https://arxiv.org/pdf/2402.10885)result as：
| Method                                       | CALVIN D-D Avg Len  |
| 3D Diffuser Actor（original） |           2.223                  | 
| Uniview Diffuser Actor  |           2.13                    | 
We only made a simple attempt and did not conduct a detailed search for parameters and structures. If you conduct more experiments, may have better results.

**Comment by mbreuss** [comment]
Thanks for sharing!
