### ISSUE TITLE
Use only the encoder

### ISSUE THREAD

**Issue by Vilonge** [liufanfanlff/RoboUniview#2]
Thanks! Very insightful work!

If I only want to train and use the vision-encoder and occupancy-decoder, without using the VLM, which parts of the codebase should I focus on? Could you provide some specific, README-like guidance?

![image](https://github.com/user-attachments/assets/0e76c0b3-9455-4a9f-8ee8-33d9fba20cee)

**Comment by Vilonge** [comment]
I noticed that some dependencies, such as the Calvin component, are missing in the codebase. How should I place them in this project?

**Comment by liufanfanlff** [comment]
> I noticed that some dependencies, such as the Calvin component, are missing in the codebase. How should I place them in this project?
You can go https://github.com/mees/calvin Download Calvin's code and replace the path of
sys.path.append('.../calvin/calvin_models')
sys.path.append('.../calvin/calvin_env')
sys.path.append('.../calvin/calvin_env/tacto_env')
  in this project.

**Comment by liufanfanlff** [comment]
> Thanks! Very insightful work!
> 
> If I only want to train and use the vision-encoder and occupancy-decoder, without using the VLM, which parts of the codebase should I focus on? Could you provide some specific, README-like guidance?
> 
> ![image](https://private-user-images.githubusercontent.com/89585131/361827495-0e76c0b3-9455-4a9f-8ee8-33d9fba20cee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MjcxOTksIm5iZiI6MTcyNDgyNjg5OSwicGF0aCI6Ii84OTU4NTEzMS8zNjE4Mjc0OTUtMGU3NmMwYjMtOTQ1NS00YTlmLThlZTgtMzNkOWZiYTIwY2VlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDA2MzQ1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2NWVjMzQxZjUzMWMyN2RhN2VjMDQ0NjZmN2EwYTJmMjM2OWZkMjYzYzQ4ZmYxYTM5YmQyNDQxNDY1ZWFhNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.61-jNcUg_--kCXSkBpGI3fgFBcjUIskzWqTK7eBOZCw)
You can follow the pretrain section in readme, which does not include VLM。

**Comment by Vilonge** [comment]
Thanks for your reply!

**Comment by Vilonge** [comment]
Sorry, I can't find new_data in codebase. So, I don't know which CalvinDataset class to use.

![9Bg5PxO2Z5](https://github.com/user-attachments/assets/51960613-b59d-45a8-99e6-883c307a3b65)

**Comment by liufanfanlff** [comment]
> Sorry, I can't find new_data in codebase. So, I don't know which CalvinDataset class to use.
> 
> ![9Bg5PxO2Z5](https://private-user-images.githubusercontent.com/89585131/362288629-51960613-b59d-45a8-99e6-883c307a3b65.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4OTc2NDIsIm5iZiI6MTcyNDg5NzM0MiwicGF0aCI6Ii84OTU4NTEzMS8zNjIyODg2MjktNTE5NjA2MTMtYjU5ZC00NWE4LTk5ZTYtODgzYzMwN2EzYjY1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDAyMDkwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3ZjRkZDZmZmQ3NjZhZjg1OWE0Y2M5NmJlODNlZGM5NjRmODA2MGIzZTViOTYwMTBkZjEyMjRhYTY0NTcyNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MUYjKKqy82X3WpTUDv-GSzFzCJHxUyhFP4AX71wVnHU)

bugfix:  new_data  ->  generate_data.py

**Comment by Vilonge** [comment]
> > Sorry, I can't find new_data in codebase. So, I don't know which CalvinDataset class to use.
> > ![9Bg5PxO2Z5](https://private-user-images.githubusercontent.com/89585131/362288629-51960613-b59d-45a8-99e6-883c307a3b65.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4OTc2NDIsIm5iZiI6MTcyNDg5NzM0MiwicGF0aCI6Ii84OTU4NTEzMS8zNjIyODg2MjktNTE5NjA2MTMtYjU5ZC00NWE4LTk5ZTYtODgzYzMwN2EzYjY1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDAyMDkwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3ZjRkZDZmZmQ3NjZhZjg1OWE0Y2M5NmJlODNlZGM5NjRmODA2MGIzZTViOTYwMTBkZjEyMjRhYTY0NTcyNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MUYjKKqy82X3WpTUDv-GSzFzCJHxUyhFP4AX71wVnHU)
> 
> bugfix: new_data -> generate_data.py

Got it!

**Comment by Vilonge** [comment]
I got a training data list by running `python3 robouniview/generate_data/generate_data.py`.
![image](https://github.com/user-attachments/assets/2c83ebda-38b4-4267-bf03-4181f75c29cc)

Now I'm trying to run `torchrun --nnodes=1 --nproc_per_node=8  robouniview/train/train.py --config config/robouniview_pretrain.yaml` to train vision encoder by occ pretrain. How should I modify the dataset path in `robouniview_pretrain,yaml`? How can I solve it with minimal modification cost? Maybe I can use single camera setting data.
![image](https://github.com/user-attachments/assets/8cb4dfba-cac7-4485-a828-5a61d3228730)

THANKS！

**Comment by liufanfanlff** [comment]
> I got a training data list by running `python3 robouniview/generate_data/generate_data.py`. ![image](https://private-user-images.githubusercontent.com/89585131/365372936-2c83ebda-38b4-4267-bf03-4181f75c29cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NTAyNDksIm5iZiI6MTcyNTk0OTk0OSwicGF0aCI6Ii84OTU4NTEzMS8zNjUzNzI5MzYtMmM4M2ViZGEtMzhiNC00MjY3LWJmMDMtNDE4MWY3NWMyOWNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDA2MzIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3MDIwNDkxZWIzYWZmMDM5MjdiZTQxMjZmOWRmZmYwYTlhMzJhNjRjMTg4NGQ3ZDI4MmQzODU3MmQzOTgwOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gn78PRpxZl0Cfk7mp44z_ymoO_o3xmk5LO8OHbOIqLM)
> 
> Now I'm trying to run `torchrun --nnodes=1 --nproc_per_node=8 robouniview/train/train.py --config config/robouniview_pretrain.yaml` to train vision encoder by occ pretrain. How should I modify the dataset path in `robouniview_pretrain,yaml`? How can I solve it with minimal modification cost? Maybe I can use single camera setting data. ![image](https://private-user-images.githubusercontent.com/89585131/365373299-8cb4dfba-cac7-4485-a828-5a61d3228730.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NTAyNDksIm5iZiI6MTcyNTk0OTk0OSwicGF0aCI6Ii84OTU4NTEzMS8zNjUzNzMyOTktOGNiNGRmYmEtY2FjNy00NDg1LWE4MjgtNWE2MWQzMjI4NzMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDA2MzIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4MzU4YTgyZWRlZjRiMTk1OTkyMTExOTVhM2E5MDVhN2JkMmRmNTgwMjdiNzNiNDllNDNjYzRhZDczZDBkM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-Q3UwKxMbMvk78VP9UPdQviYXRrqrypV-3eYfo2tWjw)
> 
> THANKS！

data_path_list: [.../new_data]
state_matrixs_path:  [.../new_data]
