### ISSUE TITLE
about the data generation

### ISSUE THREAD

**Issue by lihao0374** [liufanfanlff/RoboUniview#3]
Wonderful work! And thank you for the opensource code.

I have some questions about data generation:
1. What are the differences between [generate_data](https://github.com/liufanfanlff/RoboUniview/blob/main/robouniview/generate_data/generate_data.py) and  [generate_data_multi](https://github.com/liufanfanlff/RoboUniview/blob/main/robouniview/generate_data/generate_data_multi.py)？
2. Is  "/CALVIN/calvin_calib0" generated by the above script?
3. What are the differences between the  "/CALVIN/calvin_calib0" in pretrain yaml and "/generate_data_path_calib0" in finetune yaml?

Looking forward to your reply.

**Comment by liufanfanlff** [comment]
> Wonderful work! And thank you for the opensource code.
> 
> I have some questions about data generation:
> 
> 1. What are the differences between [generate_data](https://github.com/liufanfanlff/RoboUniview/blob/main/robouniview/generate_data/generate_data.py) and  [generate_data_multi](https://github.com/liufanfanlff/RoboUniview/blob/main/robouniview/generate_data/generate_data_multi.py)？
> 2. Is  "/CALVIN/calvin_calib0" generated by the above script?
> 3. What are the differences between the  "/CALVIN/calvin_calib0" in pretrain yaml and "/generate_data_path_calib0" in finetune yaml?
> 
> Looking forward to your reply.

1. The generate_data.py  is used to generate data with specified camera parameters (camera perspectives). The code contains three dictionaries that define three different camera perspectives. To select one, simply set cam_config to the desired. 
The generate_data_multi.py  is used to generate data with random camera parameters (camera perspectives) and is specifically used for pre-training.
2. When using generate_data.py, set cam_config = cam_config_calib0 to generate data for /CALVIN/calvin_calib0.
3. They are the same
