### ISSUE TITLE
About generate_data.py

### ISSUE THREAD

**Issue by CladernyJorn** [liufanfanlff/RoboUniview#4]
Thanks for your wonderful work! When I use `python3 robouniview/generate_data/generate_data.py` , I encountered several bugs. 
I'm not certain whether the settings of direction is correct. Can you give a more detailed instruction about how to generate multi-view data with this code?

`
sys.path.append(robouniview_path)
new_path = '.../new_calvin_ABC_D_1/'
sys.path.append(new_path+'pjt/calvin/calvin_models')
sys.path.append(new_path+'pjt/calvin/calvin_env')
sys.path.append(new_path+'pjt/calvin/calvin_env/tacto_env')
dataset_path = '.../CALVIN/task_ABC_D_formal'
...
dataset_path_env = new_path + 'env_config/'
new_calvin = new_path + 'training_npz_pcd_new/'
if not os.path.exists(new_calvin):
    os.makedirs(new_calvin)
urdf_path = new_path +'pjt/calvin/calvin_env/data/franka_panda/panda_longer_finger.urdf'
config_path = dataset_path_env + 'validation/.hydra/merged_config.yaml'
`

**Comment by liufanfanlff** [comment]
> Thanks for your wonderful work! When I use `python3 robouniview/generate_data/generate_data.py` , I encountered several bugs. I'm not certain whether the settings of direction is correct. Can you give a more detailed instruction about how to generate multi-view data with this code?
> 
> `sys.path.append(robouniview_path) new_path = '.../new_calvin_ABC_D_1/' sys.path.append(new_path+'pjt/calvin/calvin_models') sys.path.append(new_path+'pjt/calvin/calvin_env') sys.path.append(new_path+'pjt/calvin/calvin_env/tacto_env') dataset_path = '.../CALVIN/task_ABC_D_formal' ... dataset_path_env = new_path + 'env_config/' new_calvin = new_path + 'training_npz_pcd_new/' if not os.path.exists(new_calvin): os.makedirs(new_calvin) urdf_path = new_path +'pjt/calvin/calvin_env/data/franka_panda/panda_longer_finger.urdf' config_path = dataset_path_env + 'validation/.hydra/merged_config.yaml'`

We have updated the readme/generate_data section and now provide more detailed information. If you have any other questions, feel free to leave a message for further discussion.

**Comment by CladernyJorn** [comment]
Thanks for your answer. I also encountered a bug when running generate_data on TaskABC_D in `robouniview/generate_data/data.py` line 72 and 73. I am not sure why here you use glob.glob to seek the first file, I can directly load the file with file path (same as TaskD_D in line 70.
![image](https://github.com/user-attachments/assets/c281da2e-fd00-4559-a29f-6b2eb4dd8bee)

**Comment by CladernyJorn** [comment]
And I also find that the generated data has `training_1` to `training_8`, all size of the files is about 58G to 63G, except `training_7` has 511G size, I'm not sure whether it is normal?

**Comment by liufanfanlff** [comment]
> Thanks for your answer. I also encountered a bug when running generate_data on TaskABC_D in `robouniview/generate_data/data.py` line 72 and 73. I am not sure why here you use glob.glob to seek the first file, I can directly load the file with file path (same as TaskD_D in line 70. ![image](https://private-user-images.githubusercontent.com/91421658/389779336-c281da2e-fd00-4559-a29f-6b2eb4dd8bee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2NzQ5NDYsIm5iZiI6MTczMjY3NDY0NiwicGF0aCI6Ii85MTQyMTY1OC8zODk3NzkzMzYtYzI4MWRhMmUtZmQwMC00NTU5LWEyOWYtNmIyZWI0ZGQ4YmVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDAyMzA0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlZGM5NTQ5ZWI1MmM5MGRjNTZkMWU2N2M0MjM3ZDk1MDU2OTAyMGQ2MWYwMDNlNjg2ZGUzZDlmOGYyOGUyZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OXjV2XMR4sfHlA4azFKSAMZD8oSkX3oTsACKMyIL2Yg)

The seek method is related to the data storage. Our D_D storage is:
```
 - training
        *.npz
        *.npz
        ...
```
ABC_D storage is:```
 - training
         -training_1
                 *.npz
                 *.npz
         -training_2
                 *.npz
                 *.npz
        ...
```

**Comment by liufanfanlff** [comment]
> Thanks for your answer. I also encountered a bug when running generate_data on TaskABC_D in `robouniview/generate_data/data.py` line 72 and 73. I am not sure why here you use glob.glob to seek the first file, I can directly load the file with file path (same as TaskD_D in line 70. ![image](https://private-user-images.githubusercontent.com/91421658/389779336-c281da2e-fd00-4559-a29f-6b2eb4dd8bee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2NzQ5NDYsIm5iZiI6MTczMjY3NDY0NiwicGF0aCI6Ii85MTQyMTY1OC8zODk3NzkzMzYtYzI4MWRhMmUtZmQwMC00NTU5LWEyOWYtNmIyZWI0ZGQ4YmVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDAyMzA0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlZGM5NTQ5ZWI1MmM5MGRjNTZkMWU2N2M0MjM3ZDk1MDU2OTAyMGQ2MWYwMDNlNjg2ZGUzZDlmOGYyOGUyZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OXjV2XMR4sfHlA4azFKSAMZD8oSkX3oTsACKMyIL2Yg)

The seek method is related to the data storage.  D_D storage is:
```
- training
        *.npz
        *.npz
        ...
```
ABC_D is:
```
- training
         - training_1
                  *.npz
                  *.npz
                      ...
         - training_2
                  *.npz
                  *.npz
                      ...
```
